language: python

python: 3.6
env:
    - TOXENV=py27
    - TOXENV=py35
    - TOXENV=py36
    - TOXENV=pypy
    - TOXENV=pypy3
    - TOXENV=pep8
install:
    - pip install tox
script:
    - tox -e $TOXENV
